local addonName, addonPrivate = ...
setfenv(1, addonPrivate)

local L = Locales.Get("enUS")

L["greets you!"] = "greets you!"
L["Zone Changed"] = "Zone Changed"
L["Zone/Subzone"] = "Zone/Subzone"
L["Real zone/Minimap zone"] = "Real zone/Minimap zone"
L["CHECK_THE_WORLD"] = "The World"
L["CHECK_THE_WORLD_TOOLTIP"] = "Record spells cast by NPCs while questing in World zones."
L["CHECK_INSTANCES"] = "Instances"
L["CHECK_INSTANCES_TOOLTIP"] = "Record spells cast by NPCs in Dungeons, Raids, Scenarios, Arenas, and Battlegrounds."
L["Normal Dungeon"] = "Normal Dungeon"
L["Heroic Dungeon"] = "Heroic Dungeon"
L["Legacy Raid, 10 Player Normal"] = "Legacy Raid, 10 Player Normal"
L["Legacy Raid, 25 Player Normal"] = "Legacy Raid, 25 Player Normal"
L["Legacy Raid, 10 Player Heroic"] = "Legacy Raid, 10 Player Heroic"
L["Legacy Raid, 25 Player Heroic"] = "Legacy Raid, 25 Player Heroic"
L["Looking For Raid"] = "Looking For Raid"
L["Challenge Mode"] = "Challenge Mode"
L["40 Player"] = "40 Player"
L["Heroic Scenario"] = "Heroic Scenario"
L["Normal Scenario"] = "Normal Scenario"
L["Normal Raid"] = "Normal Raid"
L["Heroic Raid"] = "Heroic Raid"
L["Mythic Raid"] = "Mythic Raid"
L["Event, Raid"] = "Event, Raid"
L["Event, Party"] = "Event, Party"
L["Event, Scenario"] = "Event, Scenario"
